from django.urls import path
from . import views

urlpatterns = [

    path('', views.home, name='home'),
    path('insert/', views.insert, name='insert'),
    path('delete/', views.delete, name='delete'),
    path('quires/', views.quires, name='quires'),
    path('result/', views.result, name='result'),
    path('result1/', views.result1, name='result1'),
    path('result2/', views.result2, name='result2'),
    path('result3/', views.result3, name='result3'),
    path('result4/', views.result4, name='result4'),
    path('result5/', views.result5, name='result5'),
    path('result6/', views.result6, name='result6'),
    path('result7/', views.result7, name='result7'),
    path('result8/', views.result8, name='result8'),
    path('result9/', views.result9, name='result9'),
    path('result10/', views.result10, name='result10'),
    path('result11/', views.result11, name='result11'),
    path('result12/', views.result12, name='result12'),
    path('result13/', views.result13, name='result13'),
    path('result14/', views.result14, name='result14'),
    path('result15/', views.result15, name='result15'),
    path('result16/', views.result16, name='result16'),
    path('result17/', views.result17, name='result17'),
    path('result18/', views.result18, name='result18'),
    path('result20/', views.result20, name='result20'),
    path('result21/', views.result21, name='result21'),
    path('result22/', views.result22, name='result22'),
    path('result23/', views.result23, name='result23'),
    path('result24/', views.result24, name='result24'),
    path('result25/', views.result25, name='result25'),
    path('result26/', views.result26, name='result26'),
    path('result27/', views.result27, name='result27'),
    path('result111/', views.result111, name='result111'),
    path('result28/', views.result28, name='result28'),
    path('result29/', views.result29, name='result29'),
    path('result30/', views.result30, name='result30'),
    path('result31/', views.result31, name='result31'),
    path('result32/', views.result32, name='result32'),
    path('result33/', views.result33, name='result33'),
    path('result34/', views.result34, name='result34'),
    path('result35/', views.result35, name='result35'),
    path('result36/', views.result36, name='result36'),
    path('result37/', views.result37, name='result37'),
    path('result38/', views.result38, name='result38'),
    path('result39/', views.result39, name='result39'),
    path('result40/', views.result40, name='result40'),
    path('result41/', views.result41, name='result41'),
    path('result42/', views.result42, name='result42'),
    path('result43/', views.result43, name='result43'),
    path('result44/', views.result44, name='result44'),
    path('result45/', views.result45, name='result45'),
    path('insertOneInStructuralP1/', views.insertOneInStructuralP1, name='insertOneInStructuralP1'),
    path('delete_from_mongodb/', views.delete_from_mongodb, name='delete_from_mongodb'),

]
